[project]
name = 'Consciousness-Ascension-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.ascension-trials]
path = 'contracts/ascension-trials.clar'
clarity_version = 2
epoch = 2.5

[contracts.consciousness-milestones]
path = 'contracts/consciousness-milestones.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
